name: CD-Example
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@2
<<<<<<< HEAD
          liara deploy --app next --api-token="$LIARA_TOKEN" --region iran --detach
=======
           liara deploy --app next --api-token="$LIARA_TOKEN" --region iran --detach
>>>>>>> 2ddd9ab19facd2829ea9d52b441060673120d670
